default_env = "dev"

[[environments]]
name = "dev"
strategy = "latest"

[[environments]]
name = "prod"
strategy = "freeze"

[[projects]]
name = "nixpkgs"
url = "github:NixOS/nixpkgs/nixpkgs-unstable"

[[projects]]
name = "systems"
url = "github:nix-systems/default"

[[projects]]
name = "flake-parts"
url = "github:hercules-ci/flake-parts"

[[projects]]
name = "nix-shared"
url = "github:chadac/test-nixspace-nix-shared"
path = "./nix-shared"

[[projects]]
name = "lambda-hello-world"
url = "github:chadac/test-nixspace-lambda-hello-world"
path = "./lambda/hello-world"

[[projects]]
name = "lib-python-my-library"
url = "github:chadac/test-nixspace-lib-python-my-library"
path = "./lib/python/my-library"

[[projects]]
name = "service-rest-api"
url = "github:chadac/test-nixspace-service-rest-api"
path = "./service/rest-api"

[[projects]]
name = "config-graphql-schema"
url = "github:chadac/test-nixspace-config-graphql-schema"
path = "./config/graphql-schema"

[[projects]]
name = "service-gql-api"
url = "github:chadac/test-nixspace-service-gql-api"
path = "./service/gql-api"
